### ISSUE TITLE
correct the package name 'Tkinter'

### ISSUE THREAD

**Issue by avsingh999** [DipanshKhandelwal/Bouncing-Ball#1]
you should correct the package name 'Tkinter' to' tkinter'.

**Comment by DipanshKhandelwal** [comment]
Thanks :+1:

**Comment by DipanshKhandelwal** [comment]
@avsingh999 this file is written in python2.
#### About Tkinter/tkinter :
For **python2** it is:
```python
from Tkinter import *
```
For **python3** it is:
```python
from tkinter import *
```
Refer [this](https://stackoverflow.com/questions/17843596/difference-between-tkinter-and-tkinter).

**Comment by avsingh999** [comment]
ohh 
@DipanshKhandelwal  thanks
